.travis.yml
=> Add WCA_HOST env var to .travis.yml.

documents/policies/Competition Announcement.md
Approved by WCA Board via vote at meeting on 2018-09-07.
=> Update Competition Announcements to version 2.0

documents/policies/Competition Announcement.md
Sorry for missing this one when reviewing :disappointed:
=> Fix broken link in Competition Announcements Policy 2.0.

documents/motions/02.2019.1 - Definitions.md
=> Motion Amendments 2019 - Missing definitions/clarifications

documents/motions/02.2019.1 - Definitions.md, documents/motions/10.2017.0 - Committees and Teams.md
Changes to the motions to recognize the new Committee/Team Senior Member role
=> Motion Amendments 2019 - Committe/Team Senior Member

documents/motions/09.2019.1 - Senior Delegates.md
Fixes the issue of letting non-Full Delegates apply for Senior Delegate position.
=> Motion Amendments 2019 - Senior Delegates

documents/motions/10.2019.0 - Committees and Teams.md
Adds the debate phase for sitting Leaders and Seniors when approving a new Leader.
=> Motion Amendments 2019 - Vetting procedure

documents/motions/02.2019.1 - Definitions.md, documents/motions/20.2019.0 - Councils.md, documents/motions/20.2019.1 - Advisory Council.md
=> Motion Amendments 2019 - Advisory Council

documents/motions/10.2019.1 - Competition Announcement Team.md
=> Motion Amendments 2019 - Competition Announcement Team

documents/policies/Competition Name.md
Thanks @Jambrose777 for pointing this out!
=> Textual revision of WCA Competition Name Policy.

documents/policies/Competition Name.md
=> WCA Competition Name Policy v1.1

documents/motions/01.2019.1 - Spirit.md, documents/motions/04.2019.1 - Board of Directors.md, documents/motions/07.2017.1 - Registered Speedcubers.md, documents/motions/08.2019.1 - Delegates.md, documents/motions/09.2019.1 - Senior Delegates.md, documents/motions/10.2017.2 - Regulations Committee.md, documents/motions/10.2019.2 - Disciplinary Committee.md, documents/motions/14.2019.1 - Amendments of Regulations.md, documents/motions/16.2019.1 - Disputes.md, documents/motions/19.2017.1 - Regulations and Guidelines.md
This commit contains the changes of #8 (closed PR) and a few extra 
corrections, and fixes all the links broken in #34. It also fixes #5.
=> Textual revision of the Motions.

documents/motions/11.2019.1 - Finances.md
This PR is ready to review!
I had to add an extra space when nesting points to point 10 --  4 instead of the 3 necessary for the other points -- for the GitHub preview to show up correctly, although I'm not sure if when creating the PDF this will break anything. Any idea @jonatanklosko?
=> [MotionAmendments-March2019] Finances.

documents/motions/06.2019.1 - Regional Organizations.md
The PR is ready to be reviewed!
=> [MotionAmendments-March2019] Regional Organizations.

documents/motions/10.2019.5 - Data Protection Committee.md
=> [MotionAmendments-March2019] Data Protection Committee.

documents/motions/02.2019.1 - Definitions.md, documents/motions/04.2019.1 - Board of Directors.md, documents/motions/09.2019.1 - Senior Delegates.md, documents/motions/09.2019.2 - Regional Delegates.md, documents/motions/10.2019.4 - Quality Assurance Committee.md
:warning: This PR is not ready yet, more files need edition.
=> [MotionAmendments-March2019] Regional Delegates.

documents/policies/Equipment Funding.md
Update Equipment Funding Policy from version 1.0 to version 1.1
=> Equipment Funding Policy v1.1

documents/motions/10.2019.1 - Competition Announcement Team.md
=> [MotionAmendments-March2019] Competition Announcement Team.

documents/Code of Ethics.md
First version of the code of ethics ready to go
=> Code of Ethics v1.0

documents/motions/02.2019.1 - Definitions.md
I'm keeping the `[MotionAmendments-March2019]` on the title and the originally proposed date on files, and will add a commit fixing all of those dates when everything's ready.
=> [MotionAmendments-March2019] Policy definition.

documents/motions/09.2019.1 - Senior Delegates.md
=> [MotionAmendments-March2019] Allow Senior Delegates to demote Regional Delegates

documents/motions/10.2019.0 - Committees and Teams.md
=> [MotionAmendments-March2019] Leader selection.

documents/motions/10.2019.4 - Quality Assurance Committee.md
=> [MotionAmendments-March2019] WCA Quality Assurance Committee.

documents/motions/10.2019.2 - Disciplinary Committee.md
=> [MotionAmendments-March2019] Disciplinary Committee.

documents/motions/10.2019.3 - Ethics Committee.md
=> [MotionAmendments-March2019] Ethics Committee.

documents/motions/02.2019.1 - Definitions.md, documents/motions/04.2019.1 - Board of Directors.md, documents/motions/06.2019.1 - Regional Organizations.md, documents/motions/09.2019.1 - Senior Delegates.md, documents/motions/09.2019.2 - Regional Delegates.md, documents/motions/10.2019.0 - Committees and Teams.md, documents/motions/10.2019.1 - Competition Announcement Team.md, documents/motions/10.2019.2 - Disciplinary Committee.md, documents/motions/10.2019.3 - Ethics Committee.md, documents/motions/10.2019.4 - Quality Assurance Committee.md, documents/motions/10.2019.5 - Data Protection Committee.md, documents/motions/11.2019.1 - Finances.md
Amendments to the Motions proposed by the WCA Board of Directors.
:warning: This PR needs Staff review and approval before it can be merged.
=> Motion Amendments - June 2019

documents/policies/internal/Email Account.md
Approved by WDPC, pending Board vote.
=> WCA Email Account Policy v1.0

documents/motions/10.2019.1 - Competition Announcement Team.md
Thanks to @Epride for reporting this!
=> Fix broken link on WCAT's Motion.

documents/policies/internal/Website Posting.md
This policy is still waiting for Board approval.
=> WCA Website Posting Policy v1.0

documents/policies/internal/Delegate Probationary Status.md
Clarify that restrictions are not all-inclusive.
=> Update Delegate Probationary Status.md

documents/minutes/2019-08-06 WCA Board Meeting.md
=> Create 2019-08-06 WCA Board Meeting.md

documents/Code of Ethics.md
Fixes the wrong braces which should be parenthesis and remove a space just after that link, I'm also modifying the second link which was missing a space that exists, if this doesn't work my guess would be to try to modify the length of that line. I won't have access to my computer for a week (holidays) so I hope this works.
=> Fix markdown of the form link, and trying to fix second space

documents/motions/10.2020.0 - Committees and Teams.md, documents/motions/10.2020.1 Executive Assistants Team
Fixes #101 
Create Motion for WEAT
=> [MotionAmendments-January2020] WEAT

documents/motions/02.2020.1 - Definitions.md
Fixes #105 
Code of Ethics was out of alphabetical order.
=> [MotionAmendments-January2020] Fix Definitions

documents/motions/10.2020.2 - Competition Announcement Team.md
Fixes #122 
Allow WCAT Leader to cancel competitions.
=> [MotionAmendments-January2020] Update WCAT Motion

documents/motions/06.2020.1 - Regional Organizations.md
Fixes #125 
Require Regional Organizations to be legally registered.
Board discussed enforcement of this to begin on January 1, 2021.
=> [MotionAmendments-January2020] Regional Organizations

documents/motions/15.2020.1 - Suspensions and other Sanctions.md
Fixes #123 
Provide rights to the WEC after they conduct an investigation.
=> [MotionAmendments-January2020] Sanctions

documents/motions/08.2020.2 - Trainee Delegates.md
Fixes #124 
Create position of Trainee Delegate.
=> [MotionAmendments-January2020] Trainee Delegates

documents/minutes/2020-01-17 WCA Board Meeting.md
Add Board Meeting Minutes from 2020-01-17 meeting.
=> Create 2020-01-17 WCA Board Meeting.md

documents/minutes/2020-01-17 WCA Board Meeting.md
=> Fix heading in Board Meeting Minutes

documents/policies/external/Competition Requirements.md
Fixes https://github.com/thewca/wca-documents/issues/111.
=> WCRP Update Version 2.0

documents/policies/internal/Email Account.md
Clarify that email signatures should not contain logos or unnecessary text.
=> Update Email Account Policy

documents/policies/external/Dues System.md
=> Update Dues System

documents/motions/10.2019.2 - Disciplinary Committee.md
=> Update 10.2019.2 - Disciplinary Committee.md

documents/policies/external/Competition Safety.md
Competition Safety Policy already endorsed by the Board of Directors relating to actions taking given the recent COVID-19 situation
=> Competition Safety Policy

documents/policies/external/Competition Safety.md
Formatting fix to the scope section of the competition safety policy to that the list will display correctly
=> Competition Safety Policy formatting

documents/minutes/2020-07-19 WCA Board Meeting.md
Minutes from the meeting of the Board July 19, 2020
=> Create 2020-07-19 WCA Board Meeting.md

documents/minutes/2020-07-19 WCA Board Meeting.md
Update to include the item regarding updates to the regulations. Apologies for missing this on the original copy.
=> 2020 17 19 update

documents/policies/external/Competition Safety.md
Fixes #164 
Await Board vote before merging
=> Update Competition Safety.md

documents/motions/04.2019.1 - Board of Directors.md, documents/motions/04.2020.1 - Board of Directors.md
Changes of WCA Staff to WCA Voting Members in terms of removal of members
=> Motion Amendments September 2020 Board of Directors

documents/motions/07.2020.1 - Registered Speedcubers.md
Align motions with Bylaws regarding resignation and with current practices regarding anonymization
=> Motion Amendments September 2020 Registered Speedcubers

documents/motions/08.2020.1 - Delegates.md
Include required knowledge of WCA Policies
=> Motion Amendments September 2020 Delegates

documents/motions/08.2020.2 - Trainee Delegates.md
Remove tasks which can not be performed by a trainee Delegate
Add required knowledge of WCA Policies
=> Motions Amendments September 2020 Trainee Delegates

documents/motions/09.2020.1 - Senior Delegates.md
Edit the motion to match current practices
=> Motion Amendments September 2020 Senior Delegates

documents/motions/10.2020.3 - Quality Assurance Committee.md, documents/motions/10.2020.4 - Regulations Committee.md
Transfer of quality control tasks to WQAC instead of WRC
=> Motion Amendments September 2020 WQAC/WRC

documents/motions/10.2017.3 - Financial Committee.md, documents/motions/10.2020.5 - Financial Committee.md
Addition of collection of dues to responsibilities of WFC
=> Motion Amendments September 2020 Financial Committee

documents/motions/10.2020.6 - Data Protection Committee.md
=> Motion Amendments September 2020 Data Protection Committee

documents/motions/10.2020.0 - Committees and Teams.md
Clarification of leaderless teams
=> Motion Amendments September 2020 Committees and Teams

documents/motions/16.2020.1 - Disputes.md
Change some "musts" to "shoulds" to match current practices
=> Motion Amendments September 2020 Disputes

documents/motions/20.2020.0 - Councils.md
=> Motion Amendments September 2020 Councils

documents/motions/10.2020.7 - Ethics Committee.md
Addition of Registered Speedcubers being required to assist investigations
=> Motion Amendments September 2020 Ethics Committee

documents/Code of Ethics.md
Specifies written permission is required from the Board of Directors to have the WCA named in a contract.
=> Update to CoE 5.4

documents/motions/10.2020.3 - Quality Assurance Committee.md
Change to the wording of additions to the WAC motion based on feedback from the committee
=> Update 10.2020.3 Based on Feedback

documents/motions/08.2020.2 - Trainee Delegates.md
Changes made to Trainee Delegate Motion based on staff feedback
=> Update 08.2020.2 Based on Feedback

documents/motions/14.2020.1 - Amendments of Regulations.md
Update to the wording of the Amendments of Regulations Motion based on staff feedback
=> Update 14.2020.1 Based on Feedback

documents/motions/09.2020.1 - Senior Delegates.md, documents/motions/20.2020.0 - Councils.md
Update to Councils and Senior Delegates Motions to match the updates made to the Committees and Teams Motion
=> Update 20.2020.0 and 09.2020.1 Based on Feedback

documents/motions/09.2020.1 - Senior Delegates.md
Add Trainee Delegate to the list of role which a Senior Delegate can remove from a Delegate in their area
=> Update 09.2020.1 Based on Feedback

documents/policies/external/Competition Safety.md
Added clarification regarding the wearing of face masks while competing or judging 
Await board vote before approving
=> Competition Safety Policy Update September

documents/WCA Bylaws.md
Fix formatting of lists in updated WCA Bylaws
=> Fix Formatting of WCA Bylaws

documents/minutes/2020-10-04 WCA Annual Meeting.md
Creation of the Minutes of the WCA Annual Members Meeting 2020. These are designated as a draft as they are not officially approved until the next meeting.
=> WCA Annual Members Meeting Minutes 2020

documents/minutes/2019-10-22 WCA Annual Meeting.md
Addition of the minutes of the annual members meeting 2019 to the minutes section of the WCA website. These have been fully approved at the 2020 annual members meeting
=> WCA Annual Members Meeting Minutes 2019

documents/minutes/2020-10-24 WCA Board Meeting.md
File for the minutes of the recent Board meeting
=> Create 2020-10-24 WCA Board Meeting

documents/Code of Conduct.md
First version of the code of conduct which has been approved by the Board and is ready to be merged
=> Create Code of Conduct V1.0

documents/policies/external/Competition Safety.md
Add clarifications to the "return to competitions" section.
Approved by the Board
=> WCSP Clarifications

edudoc/delegate-crash-course/delegate_crash_course.md
=> Removed anchor links in Delegate crash course

documents/motions/15.2021.1 - Suspensions and other Sanctions.md
Clarify the right to ban a competitor from participation in or attendance of WCA competitions
=> Update 15.2020.1 - Suspensions and other Sanctions

documents/motions/10.2021.3 - Quality Assurance Committee.md, documents/motions/10.2021.8 - Quality Assurance Committee.md
Minor textual revision. No content change
=> Update 10.2020.3 Quality Assurance Committee

documents/motions/05.2021.1 - Election of Directors.md
Additional requirement for directors to be 18 years or older to align with the new bylaws.
=> Update 05.2019.01 Election of Directors

documents/motions/21.2021.01 - WCA Documents.md
Creation of a new motion to clarify an order of importance among WCA documents and how documents are maintained.
=> Create 21.2021.1 WCA Documents

documents/minutes/2021-01-31 WCA Board Meeting.md
Minutes of the regular Board Meeting held on January 31, 2021
=> Board Meeting 31-01-2021 Minutes

documents/Code of Ethics.md
As per Callum's suggestion in the CoC email thread, we moved this point to emphasize this includes Delegates AND Organizers. Also included some grammatical changes.
=> Moved 1.4.3(.1) to new point (1.5)

documents/minutes/2021-04-10 WCA Board Meeting.md
Create file for Board Minutes April 10, 2021
=> Board Minutes April 10 2021

documents/minutes/2021-06-06 WCA Board Meeting.md
Meeting minutes from June 6, 2021
=> Create Meeting Minutes June 6

documents/policies/external/Competition Requirements.md
=> Formatting Fix WCRP

documents/policies/external/Competition Requirements.md
=> Updates to WCRP

documents/policies/external/Competition Requirements.md
Updates to the competition requirements policy including the following:
- Introduction and increasing the scope of series competitions
- Changes requested in #252
=> Competition Requirements Update August 21

documents/policies/external/Competition Safety.md
=> WCSP Update

documents/minutes/2020-10-04 WCA Annual Meeting.md
Remove 1 proxy member from the count who was not represented at the meeting.
=> Update Proxy Representation

documents/minutes/2021-11-05 WCA Board Meeting.md
Create file for the minutes of the Board meeting held on November  5, 2021
=> Create Minute of Board Meeting November 2021

documents/policies/external/Competition Safety.md
Reduce to requirements, and remove the need for Senior/Region Lead review of safety plans.
Board still to vote on these changes before merging.
=> Update the WCSP to 1.7

documents/policies/external/Dues System.md
Update of the Dues System to allow Regional Organizations to adopt responsibility for paying WCA dues while also recalculating dues to be either a per country value of 5% of the registration fee.
This estimated effective date is January 1, 2022
Pending Board approval
=> Update to Dues System Policy

documents/policies/external/Dues System.md
Fixing error in the latest revision of the dues policy
=> Fix Grammatical Error in Dues Policy

edudoc/competition-templates/competition-templates-es.md, edudoc/competition-templates/competition-templates.md
Added the translation made by Gennaro Monetti and included a link to it in the English document
=> Add Spanish translation of the competition templates document

documents/policies/external/Competition Requirements.md
Clarify what to do when a venue does not have or list a maximum capacity.
=> WCRP update to 4.2

documents/motions/10.2022.1 - Archive Team.md, documents/motions/10.2022.12 - Archive Team.md
Recognize the work being done by the WCA Archive Team more officially.
=> Create 10.2022.12 - Archive Team.md

documents/motions/10.2022.13 - Sports Organization Team.md, documents/motions/10.2022.2 - Sports Organization Team.md
A Team to focus on the recognition of the WCA as a governing body of Speedcubing as a sport.
=> Create 10.2022.13 - Sports Organization Team.md

documents/motions/22.2022.1 - Major Championship Selection.md
To be more clear and consistent with how major championships are awarded by the Selection Committees.
=> Create 22.2022.1 - Major Championship Selection.md

documents/motions/02.2022.1 - Definitions.md
Add Code of Conduct to definitions, grammar fixes.
=> Add Code of Conduct to Definitions.

documents/motions/06.2022.1 - Regional Organizations.md
=> Regional Organizations grammar fix.

documents/motions/08.2022.1 - Delegates.md
Grammar fixes.
Reference Senior Delegate motion for appointments/nominations.
Avoid duplicating processes in the motions.
=> Update Delegate promotion procedure.

documents/motions/01.2021.1 - Spirit.md
No motion number update required since this is just a broken link fix.
=> Fix broken link

documents/motions/07.2021.1 - Registered Speedcubers.md
Motion number update not required as this was just a broken link.
=> Broken link fix

documents/motions/10.2022.3 - Disciplinary Committee.md
=> Specify no overlap of Board/WDC/WEC membership

documents/motions/09.2022.1 - Senior Delegates.md
Remove Board approval from the process.
=> Update Trainee promotions

edudoc/organizer-guidelines/checklist-es.md, edudoc/organizer-guidelines/checklist.md
This PR adds the Spanish translation of the competition checklist made by Gennaro Monetti
=> Add Spanish translation of the competition checklist

documents/WCA Bylaws.md
Reverts thewca/wca-documents#274
=> Revert "Fixing section references"

documents/policies/external/Dues System.md
Update to Dues System Policy for higher % of registration fees
=> Dues System Policy Update

documents/minutes/2022-10-08 WCA Annual Meeting.md
Add draft minutes of the 2022 Annual Meeting
=> Create 2022-10-08 WCA Annual Meeting

documents/policies/external/Competition Requirements.md
See commit headers for individual details.
=> WCRP Updates November 2022

documents/WCA Bylaws.md
Amend Timeline Requirement for Annual Meeting.
Pending Board vote.
=> Update WCA Bylaws 2.10

edudoc/delegate-crash-course/delegate_crash_course.md
This PR adds information on how Delegates can create business cards for themselves via VistaPrint, and includes links to internal assets for those business cards.
=> Add business card info to crash course

documents/policies/external/Competition Requirements.md
Reverts thewca/wca-documents#356 as was not approved via Board vote
=> Revert "Update Championship Naming Requirements"

documents/policies/internal/Working Group Formation.md
Creation of policy to support formation of Working Groups
=> Create Working Group Formation Policy

documents/policies/external/Competition Requirements.md
Update Competition requirements policy so that the naming requirements of Continental and World Championships match reality
=> Update Championship Naming Requirements

edudoc/organizer-guidelines/finding-venue.md
This issue was raised by some competitors at a recent UK comp, so it would be good to add this point for future organizers.
=> Add point about venue temperature to finding venue orga guideline

README.md, documents-guide.md, edudoc/competitor-tutorial/translate.txt, edudoc/judge-tutorial/translate.txt, edudoc/organizer-guidelines/translate.txt
This adds a guide for creating new documents and translating existing Educational Resources documents. It also adds a link to this document to the main README.
=> Add guide for creating new documents

edudoc/staff-crash-course/staff_crash_course.md
Broken links reported by Zain Ali.
=> Update Links in Staff Crash Course

documents/minutes/2024-01-26 WCA Board Meeting.md
Add Minutes for Board Meeting held on January 25, 2024
=> Create 2024-01-26 WCA Board Meeting

documents/minutes/2023-11-26 WCA Board Meeting.md
Add Minutes for Board Meeting November 26, 2023
=> Create 2023-11-26 WCA Board Meeting.md

documents/policies/external/Regional Organization Support.md
=> Add RO funding policy

documents/policies/external/Regional Organization Support.md
=> Update Regional Organization Support

documents/policies/external/Competition Requirements.md
[Update Log](https://docs.google.com/document/d/1ylego2XOrrILJrWJOyq3uz67cKi6Dp39mwmsTqb8oi8/edit?usp=sharing)
=> Update WCRP to 5.0

edudoc/judge-tutorial/judge-tutorial-pl.md
Update provided by Tomasz Stawowy.
=> Update Polish Translation of the Judge Tutorial

documents/Code of Ethics.md
Reverts thewca/wca-documents#400
These changes have not been approved by the Board
=> Revert "Update CoE to refer to WIC"

edudoc/judge-tutorial/judge-tutorial-pt.md
Update provided by António Gomes.
=> Update Portuguese (European) Translation of the Judge Tutorial

documents/Code of Ethics.md
Update CoE to refer to WIC.
**This PR requires Board approval. Do not merge until Board approval has been granted.**
=> Update CoE to refer to WIC

documents/Code of Conduct.md
WDC has been superseded by WIC.
=> Update CoC to refer to WIC

edudoc/delegate-handbook/delegate-handbook.md
=> Competitors' Name Changes Update in Delegate Handbook

edudoc/delegate-handbook/delegate-handbook.md
- **Removing Asia East:** Asia East recently got merged with Asia Southeast with Ming Zheng no longer being the Senior Delegate. 
- **Updating the WR submission form:** Due to some issue with the transition, a new WR submission form was created and is actively being used for submitting any WR. I had already created a [PR](https://github.com/thewca/worldcubeassociation.org/pull/9655) to update the link in the Delegate panel, so now only the Delegate handbook needs to be updated with the newer link. 
- **Clerical error:** WCA Communications Team -> WCA Communication Team
@thewca/wqac - Please review it, thank you!
=> Few fixes to the Delegate handbook

documents/motions/01.2021.1 - Spirit.md, documents/motions/10.2024.9 - Regulations Committee.md
Missing full stop in WRC's motion.
Broken link in Spirit motion.
=> Clerical fixes

.github/dependabot.yml
So that we don't run into awkward situations like #429 again :upside_down_face:
=> Add Dependabot update config for GitHub Actions

documents/motions/10.2024.4 - Appeals Committee.md
Reported by Sebastiano Tronto via email.
The base URL of the link was wrong.
=> Fix link in 10.2024.4 - Appeals Committee.md

documents/policies/external/Dues System.md
#421 but rebased so it can be merged, as discussed with @nsilvestri - changes were already approved by the WCA Board but to take effect on 1 Jan 2025
=> Implement 2025 Dues Policy Changes (v1.9 with conflicts resolved)

documents/policies/internal/Payment Authorization.md
=> Clerical Updates to Payment Authorization Policy

edudoc/guidelines-for-disciplinary-incidents/guidelines-for-disciplinary-incidents.md
Substantive:
- Expanded intro
- Expanded information on Banned Competitors list
- Expanded behavioral guidance
- Expanded information regarding WCA Volunteers
- Reworked for current Delegate Report practices
- Added general legal checkpoints
Clerical:
- Update "WCA Staff" to "WCA Volunteer"
- Updated links
- Added links
- Grammatical changes
- Reworked sections with 1st person pronouns
- WQAC provided clerical changes that were implemented
=> Update Guidelines to Disciplinary Incidents

edudoc/competitor-tutorial/tutorial.md, edudoc/guidelines-for-disciplinary-incidents/guidelines-for-disciplinary-incidents.md
The changes in #474 and #478 offset the page breaks. I've re-adjusted them accordingly.
=> Adjust Page Breaks in Edudocs

documents/policies/internal/Payment Authorization.md
Add Zak Kenny to Payment Authorization Policy for Gear Orders and Equipment funding per @EdHollingdale
=> Add Zak Kenny to Payment Authorization Policy
