thewca/wca-documents

.travis.yml

This fixes #13.
There were two options here: either put this as an encrypted env var in .travis.yml (as I've done), or make this change via the travis webui. I opted to put this in the .travis.yml file because it let me create a PR out of this, and I think it's moderately nicer to have a git history of this, but I don't feel super strongly either way.

Switch to a new personal access token.

---

documents/policies/Expense Reimbursement.md

Removes all instances of "External Staff" to comply with the January 2019 Motions (#34).

Remove External Staff from Expense Reimbursement

---

documents/policies/Competition Proximity.md

In the proximity policy, removed the argument for an exception of 16 nearby comps within the last year. Solves #48.
Of note: I was not able to successfully run the install and build scripts to ensure the PDF generated looks okay. Whenever the `sudo dpkg -i /tmp/pandoc.deb` command is run I get the error: `dpkg: error: failed to open package info file '/usr/local/var/lib/dpkg/status' for reading: No such file or directory`. It seems from here: https://github.com/Homebrew/legacy-homebrew/issues/18044 dpkg -i was removed? I haven't found much else on this.

WCA Competition Proximity Policy v1.1

---

.github/CODEOWNERS

I believe that's all we need to let this file be built automatically.
Once there is an actual content we can modify the WCA `/documents` page to link to it.

Add Code of Ethics managed by WEC

---

documents/Code of Ethics.md

The WCA (is supposed) to use the serial comma everywhere. See the WRC
style guide:
https://github.com/thewca/wca-regulations/blob/draft/style-guide.md#specific-formatting-conventions.

Add missing comma.

---

documents/policies/external/Travel Reimbursement.md

Require 60 days notice instead of 28 day notice to allow ample time for WFC and Board to review the application

Travel Reimbursement Policy - 60 day notice

---

documents/Code of Ethics.md
documents/policies/external/Competition Requirements.md

Version 1.0 to version 2.0 of the Code of Ethics after a WEC meeting and subsequent Board, Senior Delegate, and Team/Committee Leader input.

Code of Ethics update

---

documents/motions/08.2020.1 - Delegates.md

Fixes #126 
Updated Motion to say that competitions are announced by WCAT
Removed unnecessary mention of Candidate Delegates becoming Staff
Updates the Motion to explicitly require Delegates to adhere to Policies and Code of Ethics,

[MotionAmendments-January2020] Delegates

---

documents/policies/internal/Delegate Probationary Status.md

Candidate Delegates have been renamed to Junior Delegates. In this case, the type of Delegate is irrelevant, and our definition of Delegate includes Candidate (now Junior) Delegates anyway.

WCA Probationary Status Policy v1.2

---

documents/policies/external/Competition Requirements.md

Candidate Delegates have been renamed to Junior Delegates. The type of Delegate role in these cases is not necessary in temporary cases as Candidate (now Junior) Delegates and Full Delegates have the same rights and duties at competitions.

WCRP version 1.1

---

documents/Code of Ethics.md

Restructured points from section 6 to be in section 2 and 5 after communication with WCT.
Reworded 4.4 to specify that Delegates are only restricted from such apparel when they are a listed Delegate of the competition after the opposite was discovered to be an interpretation WEC did not originally mean to be construed.

Code of Ethics v2.0 to v2.1

---

edudoc/staff-crash-course/staff_crash_course.md

Clarification per past occurrences of spam sent to WCA Emails.

Clarify Whitelist issues in the Staff Crash course

---

documents/policies/external/Competition Safety.md

Allow competitions to be run without following the recommendations within the WCA Competition Safety Policy
Awaiting Board vote before merging

Allow Restriction-less Competitions

---

assets/edudoc-header.html

With the recently introduced Swedish translation #226 the `ö` and `ä` symbols were displayed incorrectly. This commit should fix such errors by allowing UTF-8 symbols in the header HTML

Allow UTF-8 symbols in edudoc headers

---

edudoc/delegate-crash-course/delegate_crash_course.md

Fix outdated links under Important Links of the WCA Delegates Crash Course

Fix outdated links in the Crash Course

---

documents/policies/external/Competition Safety.md

Allow approvals of competitions without the Board in low risk areas by a combination of the Senior Delegate, Region Lead, and WCAT.
Also has the grammar and typo fixes from #207

CSP update for low risk Countries and Regions

---

.github/workflows/pr-build.yml

Currently the only way to see what would result in the `build` branch of this repository is to build locally.
I think it would be nice to also have the resulting `build` folder from a pull request, before having to deploy it, and without having to manually create it (and also because the person manually checking it may do something a little different from what the CI does).
The easy way to solve that is simply to upload the build folder as an artifact at the end of the PR workflow.

Create an artifact with the build folder on PR

---

edudoc/competitor-tutorial/tutorial.md
edudoc/delegate-crash-course/delegate_crash_course.md
edudoc/organizer-guidelines/work-during-comp.md

- Fixes spelling errors in Competitor Tutorial and Organizer Guidelines
- Fixes typo in Delegate Crash Course (`malto` vs `mailto`)

Fix spelling errors/typos

---

documents/motions/13.2022.1 - Amendments of Motions.md

To avoid Motions updates containing typo/grammar/link fixes in future.

Allow clerical Motions fixes from the Board

---

documents/motions/08.2022.2 - Trainee Delegates.md

Additionally, remove Trainees from Delegates group but keep them in Reports.

Clarify Trainee as default appointment

---

documents/WCA Bylaws.md

Some of the references to other sections of the Bylaws are incorrect (presumably outdated). I have updated them with the sections I believe they are now supposed to direct to (it should be obvious).

Fixing section references

---

documents/motions/04.2022.1 - WCA Board.md
documents/motions/21.2022.1 - WCA Documents.md

Fixes invalid links and references to the Motions. 
As a side question, WCA Documents Motion is the only one where other Motions are just mentioned and not linked, shouldn't it be the same as in other Motions?

Fix references/links to Motions

---

edudoc/delegate-crash-course/delegate_crash_course.md

This PR just adds a sentence about the synchronize button to the paragraph about the WCA scrambles matcher in the Delegate Crash Course, as requested by the WRT

Add sentence about synchronize button in Delegate Crash Course

---

.github/workflows/deploy.yml

Changing the Github action to have the prod ip as the new host. Alternatively I could also change the deploy code to use AWS Run command, like in the deploy repo.
Thoughts?

Changed host to our prod ip

---

documents/policies/external/Dues System.md

Update to Dues policy as discussed with Board and WFC - this should now be ready for a formal Board vote. 1) Clarifies ownership of Dues setting between Board (this policy) vs WFC, 2) Clarifies some wording/terminology, 3) reduces % of registration fees paid by Bands 1 and 2 countries to 5%. 
This will be accompanied by a refresh of which countries are in which bands.

Update Dues System

---

documents/policies/external/Travel Reimbursement.md

Minor update to travel reimbursement policy proposed - the document had a mix of Treasurer only, Treasurer/Senior Member, or Treasurer/Deputy leader (which we no longer define). It is easier (and aligns with current practice) to authorise Treasurer + Senior Members for such things. 
To do in the medium term is increase documentation/governance around payment authority.

Update Travel Reimbursement

---

edudoc/delegate-crash-course/delegate_crash_course.md

Information on Trainee Delegates has not been updated since the Trainee to Junior path has been more widely standardized. This PR updates information on the track of a new Delegate to remove references to Candidate Delegates, and better explains the restrictions of a Trainee Delegate compared to a Junior or Full Delegate.
A quote by Natán has been bracketed to indicate that the original quote has been modified. Although Candidate Delegates are now better known as Junior Delegates, the intent of the statement more accurately reflects the role of the Trainee Delegate today.

Update information on Trainee Delegates

---

edudoc/delegate-crash-course/delegate_crash_course.md

This PR serves to make a few miscellaneous corrections to blatantly out-of-date information. Specifically:
* Updating the Recommending a Delegate section to account for Trainee Delegates (fixes #344)
* Updating the Acquiring Competition Equipment section to reflect updated prices and processes (supersedes #329)
* Updating references to the old proximity policy

Miscellaneous fixes

---

documents/policies/external/Competition Requirements.md

Change the naming requirements of WCA Continental and World Championships to be as per agreement with the WCA Board
fixes #348

Update Championship Naming Requirements

---

edudoc/delegate-crash-course/delegate_crash_course.md

As discussed among WRT in an email thread and shared doc.

Update to "Requesting changes to person data" - October 2023

---

README.md
bin/build.sh
edudoc/delegate-crash-course/delegate_crash_course.md
edudoc/organizer-guidelines/budget.md
edudoc/organizer-guidelines/checklist.md
edudoc/organizer-guidelines/emails.md
edudoc/organizer-guidelines/enhancing-experience.md
edudoc/organizer-guidelines/finding-venue.md
edudoc/organizer-guidelines/new-competitors.md
edudoc/organizer-guidelines/orga-team-delegate.md
edudoc/organizer-guidelines/reflection.md
edudoc/organizer-guidelines/registration.md
edudoc/organizer-guidelines/running-systems.md
edudoc/organizer-guidelines/schedule.md
edudoc/organizer-guidelines/staff.md
edudoc/organizer-guidelines/venue-setup.md
edudoc/organizer-guidelines/work-during-comp.md

Fixed:
- A lot of links with `https://worldcubeassociation.org/...` (missing subdomain). Those were replaced with wcadoc{...}.
- A lot of link in the Delegate Crash Course with the old subdomain (www). Also replaced with wcadoc{...}.
- Build script. @thewca/software-team Please check the fix, I'm not sure if the www was missing or if it was on purpose.

Fix Several Links and Build Script

---

documents/policies/external/Logo Usage.md

Updating the logo usage policy per discussion had via email w/ Board, plus additional changes regarding registered symbol.
Changes to the policy are broadly:
- Modify logos covered by the policy to those registered with USPTO
- Require the use of the Registered symbol
- Transfer logo usage approvals from the Board to WMT
- Create guidelines for the usage of the logo on personal websites

Update logo usage policy

---

documents/Code of Ethics.md

WDC and WEC have been superseded by WIC and WAC.

Update CoE to refer to WIC

---

edudoc/delegate-handbook/delegate-handbook.md

WDC and WEC have been superseded by WIC and WAC.

Update Delegate Handbook to refer to WIC

---

documents/policies/external/Competition Requirements.md

Update WCRP to 5.1 - Changes made are either clarifications or reversions to previous WCRP points.
1. Clarify scanned copies of physical records
2. Fix wording "may not" --> "must not"
3. Clarify double-checking requirement
4. Re-allow CamelCasing in competition names
5. Clarify point on unnecessary words in competition names
6. Clarify point on new registration periods

WCRP Update 5.1

---

documents/policies/internal/Deceased Registered Speedcubers.md

"Vital status" used as suggested [here](https://english.stackexchange.com/a/133950).

Simplify the WCA Deceased Registered Speedcubers Policy

---

.github/CODEOWNERS

Modifications to the CoE cannot be merged without Board approval. This removes WEC from the CODEOWNERS to more clearly communicate that Board approval is required before merging.
Also WEC no longer exists anyway.

Remove WEC from CoE CODEOWNERS

---

documents/Code of Ethics.md

(Pending review of ~~WIC~~ and Board)
As requested by WRC, addresses inconsistency between the Regs and CoE:
There was a source of confusion brought up surrounding [Regulation 1c](https://www.worldcubeassociation.org/regulations/#1c), specifically this part:
> The WCA Delegate may appoint other members of the organization team to carry out specific responsibilities on their behalf, but is ultimately accountable for how these responsibilities are carried out.
Specifically, this means that WCA Delegates may appoint someone to handle incidents on their behalf. 
The Code of Ethics currently states:
> 3.1 Decisions on incidents required to be made by a WCA Delegate must only be made by those listed on the WCA competition page.
> 3.1.1 Non-listed Delegates can make decisions on incidents only …

Fix Inconsistency Between Regs and CoE

---

documents/policies/external/Competition Requirements.md

After discussions between WCAT and WRT we have decided to update the policy on the how the years in competition names and IDs are handled. They will now be based on the first day of the competition. This will resolve a discrepancy between how years are handled between WCA IDs and competition IDs.

Update Competition Requirements.md

---

edudoc/guidelines-for-disciplinary-incidents/guidelines-for-disciplinary-incidents.md

Replace references of WDC to WIC. Small adjustments around reports of WIC members to WAC since the process is slightly different than it was with WEC/WDC.

Update Guidelines for Disc. Inc. to refer to WIC

---

assets/style.css
documents/policies/internal/Payment Authorization.md

Fixes: table not rendering + some columns go off the page.

Fix Table in WCA Payment Authorization Policy

---

.github/workflows/pr-build.yml

`upload-artifact@v2` is full deprecated and causing PR builds to fail. This uploads it to v4 which is the latest version.

Update upload-artifact to v4

---

bin/build.sh

Fixes https://github.com/thewca/wca-documents/issues/398
I'm not a bash expert, but I think this solution should be fine.
Note that I used `(([a-zA-Z0-9.\-]|[[:blank:]])+)\.md` to match the filename. I tried `[a-zA-Z0-9.\- ]`, `[a-zA-Z0-9.\-\ ]` and `[a-zA-Z0-9.\-\s]`, but none of those worked (with docker) to match spaces in the filename. That's why I added `[[:blank:]]`.
Anyway, it can be as simple as `(.+)\.md`, but I guess the complex regex should be safer.

Fix pagetitle for minutes and motions

---

.github/CODEOWNERS

WST probably does not need to be listed as the codeowner (and required therefore) for all files. This commit removes them from CODEOWNERS as a wildcard.
@thewca/software-team if you would like to own specific files or otherwise have comments on this, please let me know.

Remove WST as wildcard codeowner

---

documents/motions/10.2024.3 - Integrity Committee.md

The link to the Suspensions and Sanctions motion was outdated. It will now link to [this one](https://documents.worldcubeassociation.org/documents/motions/15.2024.1%20-%20Suspensions%20and%20other%20Sanctions.pdf).

Fix broken link in WIC motion

---

documents/policies/external/Competition Requirements.md

This reverts commit c5596dcf49d88a762f5b8e2976c4bfc54f9b93c5.
Accidentally merged prematurely, will go live January 1, 2025.

Revert "WCRP 5.3 Update (#435)"

---

edudoc/delegate-handbook/delegate-handbook.md

Replace references of "region of representation" with "country"
Not to be merged until Jan 1.
I'm somewhat surprised this was only used in the Delegate Handbook (unless I missed something).

Replace references of "region of representation" with "country"

---

documents/policies/external/Competition Requirements.md

Reverts thewca/wca-documents#444, which itself reverts thewca/wca-documents#435, thus making the changes live. 
Already approved by Board vote.

WCRP 5.3 Update

---

documents/motions/05.2025.1 - Election of Directors.md
documents/motions/08.2025.1 - Delegates.md
documents/motions/10.2024.12 - Archive Team.md
documents/motions/10.2025.0 - Committees and Teams.md
documents/motions/10.2025.1 - Communication Team.md
documents/motions/10.2025.4 - Appeals Committee.md
documents/motions/13.2025.1 - Amendments of Motions.md
documents/motions/15.2025.1 - Suspensions and other Sanctions.md
documents/motions/16.2025.1 - Disputes.md

* two cases of misspelled words ('volunteers' and 'eligible')
* one case of a verb in the wrong tense ('chose' -> 'choose')
* one case of an irregular word used when a more common word exists ('appealer' -> 'appellant')
* seven cases of missing articles ('a' or 'the')

Spelling and Grammar Errors in Motions

---

documents/policies/internal/Age.md

This PR adds a WCA Age Policy.
It must not be merged until after #450 has been merged, due to the "volunteer" language contained within.

Add WCA Age Policy v1.0

---

documents/motions/21.2024.1 - WCA Documents.md

The "Submitted by" section of the Documents Motion contains text that does not make sense in context. All other Motions say "WCA Board".
This text appears to have been included since the Motion was originally created ([PR](https://github.com/thewca/wca-documents/pull/218/files)).
This appears to be a drafting error. I believe it is suitable for correction as a clerical error under the Amendments of Motions Motion.

Documents Motion - Clerical Fix

---

documents/policies/internal/Working Group Formation.md

Slightly notable:
-Clarified that _the Board_ will evaluate the working group at the end of its term
-Clarified that conflicts of interests must be reported _to the WIC_ and linked the form
Others:
-Clerical fixes
-Aligned wording with Definitions
-Rephrasing for clarity
-Aligned stylization
-Edited ToR template to correctly abide by the WLUP

Working Group Policy Tweaks
